services:
  postgres:
    image: postgres:15-alpine
    container_name: cadastrals_postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cadastrals_network

  app:
      build:
        context: .
      container_name: cadastrals_app
      env_file: .env
      depends_on:
        postgres:
          condition: service_healthy
      ports:
      - "8000:8000"
  
      networks:
        - cadastrals_network
      restart: unless-stopped


volumes:
  postgres_data:

networks:
  cadastrals_network:
    driver: bridge
